<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByTot(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('SUM(t.total) as tot')
            ->from('AppBundle:Client','t')
            ->getQuery();
        $tot = $qb->getQuery()->getOneOrNullResult();
        return $tot;
    }
}
