<?php

namespace AppBundle\Repository;

/**
 * produit_commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produit_commandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByClient($id){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('pc')
            ->from('AppBundle:produit_commande','pc')
            ->Join('pc.client','c')

            ->Where('c.id = :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->execute();
    }
}
