<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByCat($slug)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
            $qb->select('p')
            ->from('AppBundle:produit','p')
            ->Join('p.categories','c')
            ->andWhere('c.slug = :lib')
            ->setParameter('lib', $slug);
        return $qb->getQuery()->execute();

    }
    public function getByName($slug)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('p')
            ->from('AppBundle:produit','p')
            ->Where('p.slug = :lib')
            ->setMaxResults(1)
            ->setParameter('lib', $slug)
        ;
        return $qb->getQuery()->execute()[0];

    }
    public function getByCats($slug,$slugp)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('p')
            ->from('AppBundle:produit','p')
            ->Join('p.categories','c')
            ->andWhere('c.libelle = :lib')
            ->andWhere('p.libelle != :libp')
            ->setParameter('lib', $slug)
            ->setParameter('libp',$slugp);
        return $qb->getQuery()->execute();

    }

    public function getByIds($ar){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('p')
            ->from('AppBundle:produit','p')
            ->where('p.id IN (:ar)')
            ->setParameter('ar', array_values($ar));
        return $qb->getQuery()->execute();
    }
}
